### ISSUE TITLE
SIGame: virustotal trojan detection

### ISSUE THREAD

**Issue by mdalag** [VladimirKhil/SI#129]
Please see this report
https://www.virustotal.com/gui/file/eaa209301cee5ef6e934ab6adc3f969e7cdef2c2432786668fef935b83eb38cb/behavior

What those IPs are for?
13.107.4.52:80 (TCP)
20.99.133.109:443 (TCP)

**Comment by VladimirKhil** [comment]
Thank you for information.

I have dropped a fresh clean WPF app to this site and it has been also detected as a virus. So the problem is not in SIGame itself but in this virus detection software.

https://www.virustotal.com/gui/file/fdb6f508122011fc7085332156fd41c30fb473385ba98bfb718582e7e26282a8/behavior

![image](https://user-images.githubusercontent.com/12496778/221295732-e8d60f39-68d6-4af3-a574-3c73932690e9.png)
